### ISSUE TITLE
allow players to be sorted in different orders

### ISSUE THREAD

**Issue by jdien07** [bubba0077/MegaCiv#7]
Have a toggle that allows for the five orderings:

1) VP
2) AST order
3) AST progress
4) movement (including effects of civ cards)
5) trade card drawing

**Comment by bubba0077** [comment]
All of these sorts are now available by clicking on the appropriate column (sorting by "population" considers the Military tech).

**Comment by bubba0077** [comment]
All of these sorts are now available by clicking on the appropriate column (sorting by "population" considers the Military tech).
